server:
  port: 13002
spring:
  profiles:
    active: zju
  application:
    name: spark-monitor
  http:
    encoding:
      charset: UTF-8
      force: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:edu/zju/gis/monitor/mapper/*.xml
  type-aliases-package: edu.zju.gis.monitor.entity
